### PR TITLE
Allow passing custom backend to audio-feeder

### PR DESCRIPTION
**Pull request by velochy**
Requires https://github.com/brion/audio-feeder/pull/34 to be merged to work, but should be safe even without.

### CODE REVIEW

**Comment by velochy** [comment]
@brion gentle reminder this exists :)

**Comment by brion** [comment]
Apologies, busy couple of days. :D Will review this shortly

**Comment by brion** [comment]
Merging and then tweaking per my changes

**Comment by velochy** [comment]
@brion much appreciated, thank you :)

**Pull request merged**
